### ISSUE TITLE
UI: Display insuffucient balance when submiting recovery transaction

### ISSUE THREAD

**Issue by Sednaoui** [candidelabs/security-center#8]
When a user doesn't have enough balance, make it clear in the UI that balance is not enough to perform recovery operations and pay the network fees. (In the case where the guardian is submitting a transaction, and not signing)

This case is especially true for Magic Wallet recovery, where the user often don't have funds in their guardian account.

**Comment by rabbanirizwan** [comment]
@Sednaoui kindly assign me this
